### ISSUE TITLE
Doesn't work with .pfx certs

### ISSUE THREAD

**Issue by jessepiccolo** [chef/win32-certstore#35]
I have pfx binary certs and this gem doesn't work with them.  I get the error `invalid byte sequence in UTF-8`

**Comment by piyushawasthi** [comment]
Hi @jessepiccolo this library add certificate in `OpenSSL::X509::Certificate` format. So either you can convert your `.pfx` in `OpenSSL::X509::Certificate` object or you can choose windows-cookbook that internally calling this gem (https://github.com/chef-cookbooks/windows).
Like:
```
out = powershell_out("openssl pkcs12 -in #{your_certificate_path} -nodes -passin pass:#{pfx_password}").stdout
out = File.read(source) if out.nil? || out.empty?
begin_cert = '-----BEGIN CERTIFICATE-----'
end_cert = '-----END CERTIFICATE-----'
raw = begin_cert + out[/#{begin_cert}(.*?)#{end_cert}/m, 1] + end_cert
certificate_object = OpenSSL::X509::Certificate.new raw

store = Win32::Certstore.open('Root')
store.add(certificate_object)
store.close
```

**Comment by piyushawasthi** [comment]
Hi @jessepiccolo, I am closing this issue now please feel free to reopen that in case if you will face any issue.
