### ISSUE TITLE
Error on 2 certs with same thumbprint

### ISSUE THREAD

**Issue by jordan3825** [chef/win32-certstore#60]
## Description
If two certs are in the certificate store with the same thumbprint, the code will error with `nested asn1 error`. When the code attempts to validate the cert, it runs a Powershell script to get the cert data from the Windows cert store. This code is not designed to handle the case of 2 certs being returned. When that happens the `$cert.RawData` returns $null since `$cert` is an array instead of a single cert object. 

https://github.com/chef/win32-certstore/blob/master/lib/win32/certstore/mixin/helper.rb#L34

## Gem Version
2.4.0

## Windows Version
Windows 7 x64 

Powershell Version:
```
Name                           Value
----                           -----
CLRVersion                     2.0.50727.8762
BuildVersion                   6.1.7601.17514
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1
```

## Replication Case
I am not quite sure how I got 2 certs with the same thumbprint installed. 

![2_certs](https://user-images.githubusercontent.com/10427597/73552080-93080600-4415-11ea-9840-484e737dce8a.PNG)

**Comment by johnmccrae** [comment]
Closing this out as Windows 7 is EOL now and Chef only supports Windows 10 at this point.
