### ISSUE TITLE
Readme.md states wrong ruby requirements for latest gem version (0.5.3)

### ISSUE THREAD

**Issue by rjparry** [chef/win32-certstore#72]
## Description
Just a small issue in that I noted that the readme.md still states Ruby 2.3+ is required.  This is in the Requirements section of the readme.md This is no longer the case in 0.5.3.

## Gem Version
0.5.3

## Windows Version
Windows 2016

## Replication Case
I was using Ruby 2.4 and the latest verision of this gem. I get the error (as expected) win32-certstore requires Ruby Version >= 2.5. Checking the readme.md I saw that it still states the gem is supported on Ruby 2.3 when checking the commits I can see that this is no longer the case.  It did cause a moment of confusion so I thought  I should just highlight it.

**Comment by johnmccrae** [comment]
@rjparry thanks for reporting this, I'll get it updated shortly.

**Comment by johnmccrae** [comment]
solved
